### ISSUE TITLE
文档无法从英文切换到中文

### ISSUE THREAD

**Issue by Dark15** [AnonymousAAArdvark/qi#11]
### 问题描述
文档无法从英文切换到中文
### 问题复现步骤
进入英文文档以后，点击右上角的中文按钮，会跳转到中文的文档首页，但是紧接着点击开始按钮后进入的文档依旧是英文的
### 导致问题可能的原因
中文文档首页的开始按钮链接的是英文文档而非中文文档
![image](https://user-images.githubusercontent.com/30013803/154714159-aec6652d-3729-42eb-a6f5-bd6fa5dc05e9.png)

**Comment by AnonymousAAArdvark** [comment]
谢谢
