### ISSUE TITLE
关于语法设计中的 。含义

### ISSUE THREAD

**Issue by nobodxbodon** [AnonymousAAArdvark/qi#14]
如 `系统。打印行（"一"）`，看起来对应着英文编程语言中的句点。
个人感觉，英文编程语言设计中选择句点是取其“从属”之意（比如章节号 1.2.3、A.1，版本号 3.4.0 等）而非句尾之意，而中文句点传统上只有句尾标志一种含义。
不知考虑过用其他符号如间隔号 · 吗？它可用于书名与篇（章、卷）名之间的分界。例如：[《论语·里仁》《孟子·梁惠王》《三国志·蜀志·诸葛亮传》](https://baike.baidu.com/item/%E9%97%B4%E9%9A%94%E5%8F%B7/999513)

**Comment by AnonymousAAArdvark** [comment]
· 语法更准确，但更难在键盘上输入

**Comment by nobodxbodon** [comment]
搜狗里中文下用反单引号“`”即可打出间隔号 ·

**Comment by hax** [comment]
以符合自然语言来说，像 smalltalk 那样不用额外的符号（方法调用就是个空格；句号的作用就是语句结束）才是最符合的。

`系统 打印行："一"。  // smalltalk-like syntax`

**Comment by nobodxbodon** [comment]
@hax 的确，不过这样的话和现在的类定义语法有些接近了：
```
类 吧子：丰富「
」
```
