### ISSUE TITLE
docs或官网的各种写错字了

### ISSUE THREAD

**Issue by hotmanga** [AnonymousAAArdvark/qi#4]
syntax.md文件里，保留关键字里，应该是 ”**大等**“，而不是”**打等**“。

**Comment by hotmanga** [comment]
该中文版 42 行，这句话”**分号（；）在齐语中是有意义的。它们用于分隔语句：**“中”齐语“应为”Qi语“

**Comment by hotmanga** [comment]
https://qilang.tk/#/zh-cn/operators
这个栏目应该叫”运算符“，而不是”运营商“。

**Comment by AnonymousAAArdvark** [comment]
谢谢
